name: CI

on:
  push:
    branches:
      - main
  
jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Run Tests
        run: go test

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            sunnygolang/journey:${{ steps.generate_sha.outputs.sha }}
            sunnygolang/journey:latest


#      - name: Build Docker Image
#        run: docker build -t sunnygolang/journey:${{ steps.generate_sha.outputs.sha }} .

#      - name: Push Image
#        run: |
#          docker push sunnygolang/journey:${{ steps.generate_sha.outputs.sha }}
#          docker tag sunnygolang/journey:${{ steps.generate_sha.outputs.sha }} sunnygolang/journey:latest
#          docker push sunnygolang/journey:latest

